#!/bin/sh

set -e
umask 0002

OPTIONS="--show name --hostname name --show-flags disabled --show-table name,port --flag X --polar disabled --required --unprivileged-port port"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

